# 1. Numpy

 * __Numpy provides efficient storage.__
 * __Numpy provides better ways of handling data for processing.__
 * __It is fast.__
 * __It is easy to learn.__
 * __Numpy user relatively less memeory to store data.__

# Jupyter

 * __The Jupyter Notebook is an open source web application that allows you to create line code, equations, visualizations and narrative text.__
 * __The Notebook has support for over 40 Programming languages, including Python, R, Jullia and Scala.__
 * __Notebooks can be shared with other using email,Dropbox, GitHub and the Jupyter Notebook viewers.__
 * __Your code can produce rich, interactive output HTML, images, videos, LaTeX, and many custom types.__ 

In [1]:
import numpy as np

In [2]:
# Creating array

myarray=np.array([2,3,32,7])


In [3]:
myarray

array([ 2,  3, 32,  7])

In [4]:
myarray=np.array([2,3,32,7],np.int8)
myarray

array([ 2,  3, 32,  7], dtype=int8)

In [5]:
myarray=np.array([2,3,32,7],np.int32)
myarray

array([ 2,  3, 32,  7])

In [6]:
myarray=np.array([2,3,32,7],np.int64)
myarray

array([ 2,  3, 32,  7], dtype=int64)

In [7]:
# 1-D array

myarr=np.array([3,6,37,8],np.int64)

In [8]:
myarr

array([ 3,  6, 37,  8], dtype=int64)

In [9]:
# 2-D array
myarr=np.array([[3,6,9,12]],np.int64)

In [10]:
myarr

array([[ 3,  6,  9, 12]], dtype=int64)

In [11]:
# Finding index number

print(myarr[0,0])
print(myarr[0,1])
print(myarr[0,2])
print(myarr[0,3])
#print(myarr[1,3])

3
6
9
12


In [12]:
# show details of the array

myarr.shape

(1, 4)

In [13]:
# Checking data types of array

myarr.dtype

dtype('int64')

In [14]:
myarr

array([[ 3,  6,  9, 12]], dtype=int64)

In [15]:
# how to change any element in numpy

myarr[0,1]=45   # 0 is the row index value and 1 is the column index value.


In [16]:
myarr

array([[ 3, 45,  9, 12]], dtype=int64)

In [17]:
myarr[0,3]=100


In [18]:
myarr

array([[  3,  45,   9, 100]], dtype=int64)

# Note:
* __There are 5 general mechanism for creating array:__
  * __1. Conversion from other Python structures. (eg: list, tuples).__
  * __2. Intrinsic numpy array creating object(eg: arange, one, Zeros etc).__
  * __3. Reading arrays from disk, either from standard or custom formats.__
  * __4. Creating arrays from raw bytes through the use of string of buffers.__
  * __5. Use of special library functions eg (random).__

In [20]:
listarray=np.array([[1,2,3],[5,8,5],[0,3,1]])
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [21]:
# check the data types of the array

listarray.dtype

dtype('int32')

In [22]:
# Checking the shape of any data type

listarray.shape

(3, 3)

In [23]:
# Checking size of any array

listarray.size

9

In [24]:
# Set array # Data type is object.

np.array({34,25,25,25})

array({25, 34}, dtype=object)

In [25]:
zeros=np.zeros((2,5))

In [26]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
zeros.dtype

dtype('float64')

In [38]:
range=np.arange(15)

In [39]:
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [42]:
np.linspace(2.0,3.0,num=50)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [43]:
np.linspace(2.0,3.0,num=50, endpoint=False)

array([2.  , 2.02, 2.04, 2.06, 2.08, 2.1 , 2.12, 2.14, 2.16, 2.18, 2.2 ,
       2.22, 2.24, 2.26, 2.28, 2.3 , 2.32, 2.34, 2.36, 2.38, 2.4 , 2.42,
       2.44, 2.46, 2.48, 2.5 , 2.52, 2.54, 2.56, 2.58, 2.6 , 2.62, 2.64,
       2.66, 2.68, 2.7 , 2.72, 2.74, 2.76, 2.78, 2.8 , 2.82, 2.84, 2.86,
       2.88, 2.9 , 2.92, 2.94, 2.96, 2.98])

In [46]:
lspace=np.linspace(1,5,12,endpoint=False)

In [47]:
lspace

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ,
       4.33333333, 4.66666667])

In [50]:
# empty array

emp=np.empty((4,6))

In [51]:
emp

array([[6.23042070e-307, 3.56043053e-307, 1.37961641e-306,
        9.45697982e-308, 8.01097889e-307, 1.78020169e-306],
       [7.56601165e-307, 1.02359984e-306, 8.90092016e-307,
        1.02361342e-306, 6.89804133e-307, 8.90104239e-307],
       [8.90098127e-307, 8.90111708e-307, 6.23054633e-307,
        8.90111708e-307, 6.89806849e-307, 8.90104239e-307],
       [1.42417221e-306, 1.95820216e-306, 1.24611741e-306,
        1.33511562e-306, 1.11261570e-306, 1.42410974e-306]])

In [52]:
import numpy as np

b=np.empty(2,dtype=int)   # row is 1 and column 2
print("Matrix b:\n",b)

Matrix b:
 [7536748 7340078]


In [53]:
a=np.empty([2,2], dtype=int)
print("\nMatrix a:\n",a)


Matrix a:
 [[101 109]
 [112   0]]


In [54]:
c=np.empty([3,3],dtype=int)
print('\nMatrix c: \n',c)


Matrix c: 
 [[         0          0 1787505344]
 [       531 1787504704        531]
 [1787506112        531 1913772496]]


# identity

 * __The identity array is a square array withy ones on the main diagonal.__
 * __Number of rows (and columns) in n x n output.__
 * __n x n array with its main diagonal set to one, and all other element is 0.__

In [56]:
ide=np.identity(10)
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [61]:
ide1=np.identity(100)
ide1

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [62]:
ide1.shape

(100, 100)

In [64]:
# arange() in numpy
arr=np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [70]:
# reshape

arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [81]:
arr=np.arange(100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [82]:
arr.reshape(4,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [84]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [85]:
arr.shape

(100,)

In [87]:
# Numpy array

x= [[1,2,3],[4,5,6],[7,1,0]]
x

[[1, 2, 3], [4, 5, 6], [7, 1, 0]]

In [89]:
x.shape

AttributeError: 'list' object has no attribute 'shape'

In [90]:
ar=np.array(x)

In [91]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [92]:
ar.shape

(3, 3)

In [93]:
ar.sum(axis=0)   # [12,8,9]   # addition perform by rows=0

array([12,  8,  9])

In [94]:
ar.sum(axis=1)  # [6,15,8]  # addition perform by column=1

array([ 6, 15,  8])