# 1. Numpy

 * __Numpy provides efficient storage.__
 * __Numpy provides better ways of handling data for processing.__
 * __It is fast.__
 * __It is easy to learn.__
 * __Numpy user relatively less memeory to store data.__

# Jupyter

 * __The Jupyter Notebook is an open source web application that allows you to create line code, equations, visualizations and narrative text.__
 * __The Notebook has support for over 40 Programming languages, including Python, R, Jullia and Scala.__
 * __Notebooks can be shared with other using email,Dropbox, GitHub and the Jupyter Notebook viewers.__
 * __Your code can produce rich, interactive output HTML, images, videos, LaTeX, and many custom types.__ 

In [1]:
import numpy as np

In [2]:
# Creating array

myarray=np.array([2,3,32,7])


In [3]:
myarray

array([ 2,  3, 32,  7])

In [4]:
myarray=np.array([2,3,32,7],np.int8)
myarray

array([ 2,  3, 32,  7], dtype=int8)

In [5]:
myarray=np.array([2,3,32,7],np.int32)
myarray

array([ 2,  3, 32,  7])

In [6]:
myarray=np.array([2,3,32,7],np.int64)
myarray

array([ 2,  3, 32,  7], dtype=int64)

In [7]:
# 1-D array

myarr=np.array([3,6,37,8],np.int64)

In [8]:
myarr

array([ 3,  6, 37,  8], dtype=int64)

In [9]:
# 2-D array
myarr=np.array([[3,6,9,12]],np.int64)

In [10]:
myarr

array([[ 3,  6,  9, 12]], dtype=int64)

In [11]:
# Finding index number

print(myarr[0,0])
print(myarr[0,1])
print(myarr[0,2])
print(myarr[0,3])
#print(myarr[1,3])

3
6
9
12


In [12]:
# show details of the array

myarr.shape

(1, 4)

In [13]:
# Checking data types of array

myarr.dtype

dtype('int64')

In [14]:
myarr

array([[ 3,  6,  9, 12]], dtype=int64)

In [15]:
# how to change any element in numpy

myarr[0,1]=45   # 0 is the row index value and 1 is the column index value.


In [16]:
myarr

array([[ 3, 45,  9, 12]], dtype=int64)

In [17]:
myarr[0,3]=100


In [18]:
myarr

array([[  3,  45,   9, 100]], dtype=int64)

# Note:
* __There are 5 general mechanism for creating array:__
  * __1. Conversion from other Python structures. (eg: list, tuples).__
  * __2. Intrinsic numpy array creating object(eg: arange, one, Zeros etc).__
  * __3. Reading arrays from disk, either from standard or custom formats.__
  * __4. Creating arrays from raw bytes through the use of string of buffers.__
  * __5. Use of special library functions eg (random).__

In [19]:
listarray=np.array([[1,2,3],[5,8,5],[0,3,1]])
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [20]:
# check the data types of the array

listarray.dtype

dtype('int32')

In [21]:
# Checking the shape of any data type

listarray.shape

(3, 3)

In [22]:
# Checking size of any array

listarray.size

9

In [23]:
# Set array # Data type is object.

np.array({34,25,25,25})

array({25, 34}, dtype=object)

In [24]:
zeros=np.zeros((2,5))

In [25]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
zeros.dtype

dtype('float64')

In [27]:
range=np.arange(15)

In [28]:
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [29]:
np.linspace(2.0,3.0,num=50)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [30]:
np.linspace(2.0,3.0,num=50, endpoint=False)

array([2.  , 2.02, 2.04, 2.06, 2.08, 2.1 , 2.12, 2.14, 2.16, 2.18, 2.2 ,
       2.22, 2.24, 2.26, 2.28, 2.3 , 2.32, 2.34, 2.36, 2.38, 2.4 , 2.42,
       2.44, 2.46, 2.48, 2.5 , 2.52, 2.54, 2.56, 2.58, 2.6 , 2.62, 2.64,
       2.66, 2.68, 2.7 , 2.72, 2.74, 2.76, 2.78, 2.8 , 2.82, 2.84, 2.86,
       2.88, 2.9 , 2.92, 2.94, 2.96, 2.98])

In [31]:
lspace=np.linspace(1,5,12,endpoint=False)

In [32]:
lspace

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ,
       4.33333333, 4.66666667])

In [33]:
# empty array

emp=np.empty((4,6))

In [34]:
emp

array([[9.24086089e-312, 7.65801751e-322, 0.00000000e+000,
        0.00000000e+000, 8.01097888e-307, 1.16095484e-028],
       [6.01729664e+175, 2.64937383e+180, 1.14073631e+243,
        7.35874688e+223, 3.27340050e+132, 3.77075671e+233],
       [3.57472422e+161, 1.94216729e-109, 8.29655075e-114,
        7.65791870e-096, 8.82142681e+199, 1.96101067e+243],
       [4.07186895e+223, 6.74421134e+217, 3.42664522e-062,
        8.93168689e+271, 4.98131536e+151, 1.94920670e-153]])

In [35]:
import numpy as np

b=np.empty(2,dtype=int)   # row is 1 and column 2
print("Matrix b:\n",b)

Matrix b:
 [1853189987  540680820]


In [36]:
a=np.empty([2,2], dtype=int)
print("\nMatrix a:\n",a)


Matrix a:
 [[1819636581 1713402740]
 [1931506287 1819042157]]


In [37]:
c=np.empty([3,3],dtype=int)
print('\nMatrix c: \n',c)


Matrix c: 
 [[         0          0 2060278000]
 [       435 2060275888        435]
 [2060275952        435       5792]]


# identity

 * __The identity array is a square array withy ones on the main diagonal.__
 * __Number of rows (and columns) in n x n output.__
 * __n x n array with its main diagonal set to one, and all other element is 0.__

In [38]:
ide=np.identity(10)
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [39]:
ide1=np.identity(100)
ide1

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [40]:
ide1.shape

(100, 100)

In [41]:
# arange() in numpy
arr=np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [42]:
# reshape

arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [43]:
arr=np.arange(100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [44]:
arr.reshape(4,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [45]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [46]:
arr.shape

(100,)

In [47]:
# Numpy array

x= [[1,2,3],[4,5,6],[7,1,0]]
x

[[1, 2, 3], [4, 5, 6], [7, 1, 0]]

In [48]:
x.shape

AttributeError: 'list' object has no attribute 'shape'

In [49]:
ar=np.array(x)

In [50]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [51]:
ar.shape

(3, 3)

In [52]:
ar.sum(axis=0)   # [12,8,9]   # addition perform by rows=0

array([12,  8,  9])

In [53]:
ar.sum(axis=1)  # [6,15,8]  # addition perform by column=1

array([ 6, 15,  8])

# Transpose() 

 * __With the help of Numpy numpy.transpose(), we can perform the simple function of transpose within one line using numpy.transpose() method of numpy. It can transpose the 2-D arrays on the other hand it has no effect on 1-D arrays. This method transpose the 2-D numpy array.__

In [54]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [55]:
# Tanspose
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [56]:
# iterators 

ar.flat   

In [57]:
for items in ar.flat:
    print(items)

1
2
3
4
5
6
7
1
0


In [58]:
# how to check dimension in array.

ar.ndim

2

In [59]:
# how to check size of the size

ar.size

9

In [60]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [61]:
ar.nbytes

36

In [62]:
one=np.array([1,2,3,4,6,634])    # 1-D

one

array([  1,   2,   3,   4,   6, 634])

In [63]:
one.size

6

In [64]:
one.nbytes

24

 * __The main difference between attributes and method is that attributes are data, while method are action. This means that attributes store information, while methods perform actions. For example, an attribute might store the name of the array, while a method might be a function that calculates the sum of the slements of an array. To call an attribute, you can use the same dot notation and add parentheses, like this:__
 * __array.attributes*__
 * __array.method(argument1,argument2)__

In [67]:
one

array([  1,   2,   3,   4,   6, 634])

In [69]:
one.argmax()   # This is the index value of maximum number in the array

5

In [70]:
one.argmin()  # This returns the minimum number in the array.

0

In [71]:
# argsort

one

array([  1,   2,   3,   4,   6, 634])

In [73]:
two=np.array([10,15,7,8,20,9,200,15])

In [74]:
two

array([ 10,  15,   7,   8,  20,   9, 200,  15])

In [75]:
two.argsort()    # ascending order

array([2, 3, 5, 0, 1, 7, 4, 6], dtype=int64)

In [77]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [78]:
ar.argmin()   # column index

8

In [80]:
ar.argmax()

6

In [81]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [82]:
ar.argmax(axis=0)   # rows

array([2, 1, 1], dtype=int64)

In [83]:
ar.argmax(axis=1)   #by column

array([2, 2, 0], dtype=int64)

In [84]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [86]:
ar.argsort(axis=1)  #[0,1,2],[0,1,2],[2,1,0] # by column


array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [87]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [89]:
ar.argsort(axis=0)  # arranged by rows.

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [91]:
# ravel 

ar.ravel()   # arranged in sequence form.

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [92]:
# reshape

ar.reshape(9,1)  # 9 rows and 1 column # 9X1 9

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [93]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [94]:
ar2=np.array([[1,2,1],[4,0,6],[8,1,0]])
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [95]:
# Add two array
ar+ar2  # add this array by column method.

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [96]:
x=[324,34]+[34,546]
x    # If you performing list addition then addition is not allowed.

[324, 34, 34, 546]

In [97]:
# multiplying two array

ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [98]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [99]:
ar*ar2  # multiplied by column method i.e by default

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [100]:
# how to find the square root of the array if possible
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [101]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [102]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [103]:
np.sqrt(ar2)

array([[1.        , 1.41421356, 1.        ],
       [2.        , 0.        , 2.44948974],
       [2.82842712, 1.        , 0.        ]])

In [104]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [105]:
# sum of all element in the array.
ar.sum()

29

In [106]:
ar.max()

7

In [107]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [108]:
ar2.max()

8

In [109]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [110]:
np.where(ar>3)  # it gives the index value greater than 3 by rows and by ascending order

(array([1, 1, 1, 2], dtype=int64), array([0, 1, 2, 0], dtype=int64))

In [112]:
np.where(ar>4)  #[1,1,2]

(array([1, 1, 2], dtype=int64), array([1, 2, 0], dtype=int64))

In [113]:
np.where(ar>5) #

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [117]:
# Zeros  # It counts total value of non zeros in your array

np.count_nonzero(ar)

8

In [118]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [119]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))