# 1. Numpy

 * __Numpy provides efficient storage.__
 * __Numpy provides better ways of handling data for processing.__
 * __It is fast.__
 * __It is easy to learn.__
 * __Numpy user relatively less memeory to store data.__

# Jupyter

 * __The Jupyter Notebook is an open source web application that allows you to create line code, equations, visualizations and narrative text.__
 * __The Notebook has support for over 40 Programming languages, including Python, R, Jullia and Scala.__
 * __Notebooks can be shared with other using email,Dropbox, GitHub and the Jupyter Notebook viewers.__
 * __Your code can produce rich, interactive output HTML, images, videos, LaTeX, and many custom types.__ 

In [1]:
import numpy as np

In [2]:
# Creating array

myarray=np.array([2,3,32,7])


In [3]:
myarray

array([ 2,  3, 32,  7])

In [4]:
myarray=np.array([2,3,32,7],np.int8)
myarray

array([ 2,  3, 32,  7], dtype=int8)

In [5]:
myarray=np.array([2,3,32,7],np.int32)
myarray

array([ 2,  3, 32,  7])

In [6]:
myarray=np.array([2,3,32,7],np.int64)
myarray

array([ 2,  3, 32,  7], dtype=int64)

In [7]:
# 1-D array

myarr=np.array([3,6,37,8],np.int64)

In [8]:
myarr

array([ 3,  6, 37,  8], dtype=int64)

In [9]:
# 2-D array
myarr=np.array([[3,6,9,12]],np.int64)

In [10]:
myarr

array([[ 3,  6,  9, 12]], dtype=int64)

In [11]:
# Finding index number

print(myarr[0,0])
print(myarr[0,1])
print(myarr[0,2])
print(myarr[0,3])
#print(myarr[1,3])

3
6
9
12


In [12]:
# show details of the array

myarr.shape

(1, 4)

In [13]:
# Checking data types of array

myarr.dtype

dtype('int64')

In [14]:
myarr

array([[ 3,  6,  9, 12]], dtype=int64)

In [15]:
# how to change any element in numpy

myarr[0,1]=45   # 0 is the row index value and 1 is the column index value.


In [16]:
myarr

array([[ 3, 45,  9, 12]], dtype=int64)

In [17]:
myarr[0,3]=100


In [18]:
myarr

array([[  3,  45,   9, 100]], dtype=int64)

# Note:
* __There are 5 general mechanism for creating array:__
  * __1. Conversion from other Python structures. (eg: list, tuples).__
  * __2. Intrinsic numpy array creating object(eg: arange, one, Zeros etc).__
  * __3. Reading arrays from disk, either from standard or custom formats.__
  * __4. Creating arrays from raw bytes through the use of string of buffers.__
  * __5. Use of special library functions eg (random).__

In [19]:
listarray=np.array([[1,2,3],[5,8,5],[0,3,1]])
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [20]:
# check the data types of the array

listarray.dtype

dtype('int32')

In [21]:
# Checking the shape of any data type

listarray.shape

(3, 3)

In [22]:
# Checking size of any array

listarray.size

9

In [23]:
# Set array # Data type is object.

np.array({34,25,25,25})

array({25, 34}, dtype=object)

In [24]:
zeros=np.zeros((2,5))

In [25]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
zeros.dtype

dtype('float64')

In [27]:
range=np.arange(15)

In [28]:
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [29]:
np.linspace(2.0,3.0,num=50)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [30]:
np.linspace(2.0,3.0,num=50, endpoint=False)

array([2.  , 2.02, 2.04, 2.06, 2.08, 2.1 , 2.12, 2.14, 2.16, 2.18, 2.2 ,
       2.22, 2.24, 2.26, 2.28, 2.3 , 2.32, 2.34, 2.36, 2.38, 2.4 , 2.42,
       2.44, 2.46, 2.48, 2.5 , 2.52, 2.54, 2.56, 2.58, 2.6 , 2.62, 2.64,
       2.66, 2.68, 2.7 , 2.72, 2.74, 2.76, 2.78, 2.8 , 2.82, 2.84, 2.86,
       2.88, 2.9 , 2.92, 2.94, 2.96, 2.98])

In [31]:
lspace=np.linspace(1,5,12,endpoint=False)

In [32]:
lspace

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ,
       4.33333333, 4.66666667])

In [33]:
# empty array

emp=np.empty((4,6))

In [34]:
emp

array([[3.56043053e-307, 1.37961641e-306, 9.45697982e-308,
        8.01097889e-307, 1.78020169e-306, 7.56601165e-307],
       [1.02359984e-306, 1.33510679e-306, 2.22522597e-306,
        1.33511018e-306, 6.23057689e-307, 1.86921279e-306],
       [8.90098127e-307, 1.78020848e-306, 1.60219035e-306,
        1.42418172e-306, 8.06610070e-308, 6.89810244e-307],
       [1.22387550e-307, 2.22522596e-306, 8.34423917e-308,
        1.11261162e-306, 1.78021527e-306, 6.95309593e-310]])

In [35]:
import numpy as np

b=np.empty(2,dtype=int)   # row is 1 and column 2
print("Matrix b:\n",b)

Matrix b:
 [-965017600      32766]


In [36]:
a=np.empty([2,2], dtype=int)
print("\nMatrix a:\n",a)


Matrix a:
 [[898959984       423]
 [        0         0]]


In [37]:
c=np.empty([3,3],dtype=int)
print('\nMatrix c: \n',c)


Matrix c: 
 [[        0         0 932700672]
 [      423 932701184       423]
 [932701696       423   7209065]]


# identity

 * __The identity array is a square array withy ones on the main diagonal.__
 * __Number of rows (and columns) in n x n output.__
 * __n x n array with its main diagonal set to one, and all other element is 0.__

In [38]:
ide=np.identity(10)
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [39]:
ide1=np.identity(100)
ide1

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [40]:
ide1.shape

(100, 100)

In [41]:
# arange() in numpy
arr=np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [42]:
# reshape

arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [43]:
arr=np.arange(100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [44]:
arr.reshape(4,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [45]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [46]:
arr.shape

(100,)

In [47]:
# Numpy array

x= [[1,2,3],[4,5,6],[7,1,0]]
x

[[1, 2, 3], [4, 5, 6], [7, 1, 0]]

In [48]:
x.shape

AttributeError: 'list' object has no attribute 'shape'

In [49]:
ar=np.array(x)

In [50]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [51]:
ar.shape

(3, 3)

In [52]:
ar.sum(axis=0)   # [12,8,9]   # addition perform by rows=0

array([12,  8,  9])

In [53]:
ar.sum(axis=1)  # [6,15,8]  # addition perform by column=1

array([ 6, 15,  8])

# Transpose() 

 * __With the help of Numpy numpy.transpose(), we can perform the simple function of transpose within one line using numpy.transpose() method of numpy. It can transpose the 2-D arrays on the other hand it has no effect on 1-D arrays. This method transpose the 2-D numpy array.__

In [54]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [55]:
# Tanspose
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [56]:
# iterators 

ar.flat   

In [57]:
for items in ar.flat:
    print(items)

1
2
3
4
5
6
7
1
0


In [58]:
# how to check dimension in array.

ar.ndim

2

In [59]:
# how to check size of the size

ar.size

9

In [60]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [61]:
ar.nbytes

36

In [62]:
one=np.array([1,2,3,4,6,634])    # 1-D

one

array([  1,   2,   3,   4,   6, 634])

In [63]:
one.size

6

In [64]:
one.nbytes

24

 * __The main difference between attributes and method is that attributes are data, while method are action. This means that attributes store information, while methods perform actions. For example, an attribute might store the name of the array, while a method might be a function that calculates the sum of the slements of an array. To call an attribute, you can use the same dot notation and add parentheses, like this:__
 * __array.attributes*__
 * __array.method(argument1,argument2)__

In [65]:
one

array([  1,   2,   3,   4,   6, 634])

In [66]:
one.argmax()   # This is the index value of maximum number in the array

5

In [67]:
one.argmin()  # This returns the minimum number in the array.

0

In [68]:
# argsort

one

array([  1,   2,   3,   4,   6, 634])

In [69]:
two=np.array([10,15,7,8,20,9,200,15])

In [70]:
two

array([ 10,  15,   7,   8,  20,   9, 200,  15])

In [71]:
two.argsort()    # ascending order

array([2, 3, 5, 0, 1, 7, 4, 6], dtype=int64)

In [72]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [73]:
ar.argmin()   # column index

8

In [74]:
ar.argmax()

6

In [75]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [76]:
ar.argmax(axis=0)   # rows

array([2, 1, 1], dtype=int64)

In [77]:
ar.argmax(axis=1)   #by column

array([2, 2, 0], dtype=int64)

In [78]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [79]:
ar.argsort(axis=1)  #[0,1,2],[0,1,2],[2,1,0] # by column


array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [80]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [81]:
ar.argsort(axis=0)  # arranged by rows.

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [82]:
# ravel 

ar.ravel()   # arranged in sequence form.

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [83]:
# reshape

ar.reshape(9,1)  # 9 rows and 1 column # 9X1 9

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [84]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [85]:
ar2=np.array([[1,2,1],[4,0,6],[8,1,0]])
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [86]:
# Add two array
ar+ar2  # add this array by column method.

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [87]:
x=[324,34]+[34,546]
x    # If you performing list addition then addition is not allowed.

[324, 34, 34, 546]

In [88]:
# multiplying two array

ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [89]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [90]:
ar*ar2  # multiplied by column method i.e by default

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [91]:
# how to find the square root of the array if possible
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [92]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [93]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [94]:
np.sqrt(ar2)

array([[1.        , 1.41421356, 1.        ],
       [2.        , 0.        , 2.44948974],
       [2.82842712, 1.        , 0.        ]])

In [95]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [96]:
# sum of all element in the array.
ar.sum()

29

In [97]:
ar.max()

7

In [98]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [99]:
ar2.max()

8

In [100]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [101]:
np.where(ar>3)  # it gives the index value greater than 3 by rows and by ascending order

(array([1, 1, 1, 2], dtype=int64), array([0, 1, 2, 0], dtype=int64))

In [102]:
np.where(ar>4)  #[1,1,2]

(array([1, 1, 2], dtype=int64), array([1, 2, 0], dtype=int64))

In [103]:
np.where(ar>5) #

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [104]:
# Zeros  # It counts total value of non zeros in your array

np.count_nonzero(ar)

8

In [105]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [106]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

# Numerical Operations On Numpy Array

# Using Scalars

In [107]:
import numpy as np

lst=[2,3,7.9,3.3,6.9,0.11,10.3,12.9]
v=np.array(lst)
v

array([ 2.  ,  3.  ,  7.9 ,  3.3 ,  6.9 ,  0.11, 10.3 , 12.9 ])

In [108]:
v.dtype

dtype('float64')

In [109]:
v=v+2
v

array([ 4.  ,  5.  ,  9.9 ,  5.3 ,  8.9 ,  2.11, 12.3 , 14.9 ])

In [110]:
print(v)

[ 4.    5.    9.9   5.3   8.9   2.11 12.3  14.9 ]


In [111]:
print(v*2)

[ 8.   10.   19.8  10.6  17.8   4.22 24.6  29.8 ]


In [112]:
print(v-1.38)

[ 2.62  3.62  8.52  3.92  7.52  0.73 10.92 13.52]


In [113]:
print(v)

[ 4.    5.    9.9   5.3   8.9   2.11 12.3  14.9 ]


In [114]:
print(v**2)

[ 16.      25.      98.01    28.09    79.21     4.4521 151.29   222.01  ]


In [115]:
print(v**1.5)

[ 8.         11.18033989 31.14962279 12.2015163  26.55125232  3.06495204
 43.13776768 57.51477202]


In [116]:
result=[]
lst=[2,3,7.9,3.3,6.9,0.11,10.3,12.9]

for i in lst:
    i=i+2
    result.append(i)
print(result)
   # +2 result

[4, 5, 9.9, 5.3, 8.9, 2.11, 12.3, 14.9]


In [117]:
x=[]
print(lst)
for val in lst:
    x.append(val+4)
print(x)

[2, 3, 7.9, 3.3, 6.9, 0.11, 10.3, 12.9]
[6, 7, 11.9, 7.3, 10.9, 4.11, 14.3, 16.9]


In [118]:
res=[val +2 for val in lst]
print(res)

[4, 5, 9.9, 5.3, 8.9, 2.11, 12.3, 14.9]


In [119]:
lst

[2, 3, 7.9, 3.3, 6.9, 0.11, 10.3, 12.9]

# Arithmetic operations with two arrays.

In [120]:
a=np.array([[11,12,13],[21,22,23],[31,32,33]])
b=np.ones((3,3))

print('Adding to arrays:')
print(a+b)

Adding to arrays:
[[12. 13. 14.]
 [22. 23. 24.]
 [32. 33. 34.]]


In [121]:
b=np.ones((3,3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [122]:
print(a)
print(b)

[[11 12 13]
 [21 22 23]
 [31 32 33]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [123]:
print('Multiplying two arrays:')
print(a*(b+3))

Multiplying two arrays:
[[ 44.  48.  52.]
 [ 84.  88.  92.]
 [124. 128. 132.]]


# Definition of the dot product


 * __The dot product is defined like this:__
 * __dot(a,b, out=None)__

In [124]:
print(np.dot(3,4))

x=np.array([3])
y=np.array([4])
print(x.ndim)

12
1


In [125]:
x=np.array([3,-2])
y=np.array([-4,1])

print(x.ndim)

print(np.dot(x,y))

1
-14


In [126]:
array1=np.array([1,2,3])
array2=np.array([4,5,6])
dot_product=np.dot(array1,array2)
print(dot_product)

32


In [127]:
a=np.array([[1,2,3],[3,2,1]])
b=np.array([[2,3,4,-2],[1,-1,2,3],[1,2,3,0]])

print(a)
print(b)

print(a.shape)
print(b.shape)

print(np.dot(a,b))

[[1 2 3]
 [3 2 1]]
[[ 2  3  4 -2]
 [ 1 -1  2  3]
 [ 1  2  3  0]]
(2, 3)
(3, 4)
[[ 7  7 17  4]
 [ 9  9 19  0]]


In [128]:
x=np.array([[[3,1,2],[4,2,2]],
            [[-1,0,1],[1,-1,-2]],
            [[3,2,2],[4,4,3]],
            [[2,2,1],[3,1,3]]])
y=np.array([[[2,3,1,2,1],
             [2,2,2,0,0],
             [3,4,0,1,-1]],
            [[1,4,3,2,2],
             [4,1,1,4,-3],
             [4,1,0,3,0]]])
print('x.shpae:',x.shape,'x.ndmin:',x.ndim)
print('y.shpae:',y.shape,'y.ndmin:',y.ndim)


r=np.dot(x,y)
print(r)

x.shpae: (4, 2, 3) x.ndmin: 3
y.shpae: (2, 3, 5) y.ndmin: 3
[[[[ 14  19   5   8   1]
   [ 15  15  10  16   3]]

  [[ 18  24   8  10   2]
   [ 20  20  14  22   2]]]


 [[[  1   1  -1  -1  -2]
   [  3  -3  -3   1  -2]]

  [[ -6  -7  -1   0   3]
   [-11   1   2  -8   5]]]


 [[[ 16  21   7   8   1]
   [ 19  16  11  20   0]]

  [[ 25  32  12  11   1]
   [ 32  23  16  33  -4]]]


 [[[ 11  14   6   5   1]
   [ 14  11   8  15  -2]]

  [[ 17  23   5   9   0]
   [ 19  16  10  19   3]]]]


# Matrices vs Two-Dimensional arrays

In [129]:
x1 = np.array([[1,2,3],[2,2,2],[3,3,3]])
y1 =np.array([[3,2,1],[1,2,3],[-1,-2,-3]])

r1=x1*y1
print(r1)

#[3,4,3],[2,4,6],[-3,-6,-9]

[[ 3  4  3]
 [ 2  4  6]
 [-3 -6 -9]]


# Comparison Opertors

In [130]:
a2=np.array([[11,12,13],[21,22,23],[31,32,33]])
b2=np.array([[11,102,13],[201,22,23],[31,32,303]])

a2==b2

array([[ True, False,  True],
       [False,  True,  True],
       [ True,  True, False]])

In [131]:
a2>=b2

array([[ True, False,  True],
       [False,  True,  True],
       [ True,  True, False]])

In [132]:
a2<b2

array([[False,  True, False],
       [ True, False, False],
       [False, False,  True]])

In [133]:
a2<=b2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [134]:
a2!=b2

array([[False,  True, False],
       [ True, False, False],
       [False, False,  True]])

In [135]:
a2>b2

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [136]:
a2

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [137]:
b2

array([[ 11, 102,  13],
       [201,  22,  23],
       [ 31,  32, 303]])

In [138]:
a3=np.array([[True,True],[False,False]])
a4= np.array([[True,False],[True,False]])

print(np.logical_and(a3,a4))

print(np.logical_or(a3,a4)) 

[[ True False]
 [False False]]
[[ True  True]
 [ True False]]


# Applying operators on arrays with different shpaes

In [139]:
a1=np.array([[11,12,13],[21,22,23],[31,32,33]])
a2=np.array([1,2,3])

print(a1*a2)

[[11 24 39]
 [21 44 69]
 [31 64 99]]


In [140]:
print(a1+a2)

[[12 14 16]
 [22 24 26]
 [32 34 36]]


In [141]:
print(a1/a2)    #float

[[11.          6.          4.33333333]
 [21.         11.          7.66666667]
 [31.         16.         11.        ]]


In [142]:
print(a1//a2)

[[11  6  4]
 [21 11  7]
 [31 16 11]]


In [143]:
print(a1**a2)

[[   11   144  2197]
 [   21   484 12167]
 [   31  1024 35937]]


# Numpy Arrays: Concatenationg, Flattening and Adding Dimension

In [144]:
a = np.array([[[0,1],
               [2,3],
               [4,5],
               [6,7]],
              [[8,9],
               [10,11],
               [12,13],
               [14,15]],
              [[16,17],
               [18,19],
               [20,21],
               [21,23]]])
x=a.flatten()
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 21 23]


In [145]:
x.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 21, 23])

In [146]:
# 7301530985 

In [147]:
# 1. Create an one dimensional array called "V".
# 2. Create a new array consists of the odd indices of previously created array "V".
# 3. Create a new array backwards ordering from v.
# 4. What will be the output of the following code:
    # a= np.array([1,2,3,4,5])
    # b=a[1:4]
    # b[0]=200
    # print(a[1])
# 5. Create two dimensional array called "m".
# 6. Create a new array from m, in which the elements of each row are in reverse order.
# 7. Another one, where the rows are in reverse order.
# 8. Create an array from m, where columns and rows are in reverse order.
# 9. Cut of the first and last row and the first and last column.

In [148]:
import numpy as np
v=np.array([5,7,9,3,44,68,25,74,11,4,27,33,8])
x=[]
for i in v:
    if i%2!=0:
        x.append(i)

n=np.array([x])
print(n)

[[ 5  7  9  3 25 11 27 33]]


In [149]:
# 1. Create an one dimensional array called "V".

a = np.array([3,8,12,18,7,11,30])
a

array([ 3,  8, 12, 18,  7, 11, 30])

In [150]:
# 2. Create a new array consists of the odd indices of previously created array "V".
v = np.array([3,8,12,18,7,11,30])
x=[]
for i in v:
    if i%2!=0:
        x.append(i)

n=np.array([x])
print(n)

[[ 3  7 11]]


In [151]:
# another method
v = np.array([3,8,12,18,7,11,30])
odd_element=v[::2]
print(odd_element)

[ 3 12  7 30]


In [152]:
# 3. Create a new array backwards ordering from v.
print(v)
reverse_order=v[::-1]
print(reverse_order)

[ 3  8 12 18  7 11 30]
[30 11  7 18 12  8  3]


In [153]:
# 4. What will be the output of the following code:
    # a= np.array([1,2,3,4,5])
    # b[0]=200
    # print(a[1])

a= np.array([1,2,3,4,5])
b=a[1:4]  # slicing method
print(b)
b[0]=200
print(b)
print(b[0])
print(a[1])

[2 3 4]
[200   3   4]
200
200


In [154]:
# 5. Create two dimensional array called "m".

m=np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])

m

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

In [155]:
# 6. Create a new array from m, in which the elements of each row are in reverse order.
print(m)
m[::,::-1]

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


array([[14, 13, 12, 11],
       [24, 23, 22, 21],
       [34, 33, 32, 31]])

In [156]:
# 7. Another one, where the rows are in reverse order.
print(m)
m[::-1]

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


array([[31, 32, 33, 34],
       [21, 22, 23, 24],
       [11, 12, 13, 14]])

In [157]:
# 8. Create an array from m, where columns and rows are in reverse order.
print(m)
m[::-1,::-1]

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


array([[34, 33, 32, 31],
       [24, 23, 22, 21],
       [14, 13, 12, 11]])

In [158]:
# 9. Cut of the first and last row and the first and last column.
print(m)
m[1:-1,1:-1]

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


array([[22, 23]])

In [159]:
ar=np.array([[1,2,3],
             [4,5,6],
             [7,1,0]])

ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [160]:

np.max(ar)

7

In [161]:
# condition applied in array to finding the max value in the array.
np.where(ar>3)   # [4,5,6,7]

(array([1, 1, 1, 2], dtype=int64), array([0, 1, 2, 0], dtype=int64))

In [162]:
np.where(ar>4)

(array([1, 1, 2], dtype=int64), array([1, 2, 0], dtype=int64))

In [163]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [164]:
np.where(ar<2)

(array([0, 2, 2], dtype=int64), array([0, 1, 2], dtype=int64))

In [165]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

# Random Number and Probability

In [166]:
# dice=[1,2,3,4,5,6]

In [167]:
import random

random_number=random.random()
print(random_number)

0.1825325032638735


In [168]:
x=random.SystemRandom()
[x.random() for _ in range(10)]

TypeError: 'numpy.ndarray' object is not callable

In [169]:
outcome=random.randint(1,6)
print(outcome)

2


In [170]:
# [1,6] [10]

# [1,2,3,4,5,6,1,3,5,4]

[random.randint(1,6) for _ in range(10) ]

TypeError: 'numpy.ndarray' object is not callable

In [171]:
outcome=np.random.randint(1,6,size=10)
print(outcome)

[1 3 3 5 2 1 2 4 1 3]


In [172]:
print(np.random.randint(1,7))
print(np.random.randint(1,7,size=10))

print(np.random.randint(1,7,size=(10,)))
print(np.random.randint(1,7,size=(5,4)))

6
[4 2 3 4 6 5 1 3 1 2]
[1 2 1 4 3 4 3 5 3 6]
[[4 2 1 3]
 [6 5 1 1]
 [4 2 2 1]
 [1 6 6 3]
 [6 4 3 4]]


# Random choices with Python

In [173]:
from random import choice
possible_destinations=["Berlin","Hamburg","Munich","Amsterdam","London","Paris","Zurich",
                       "Heidelberg","Strasbourg","Augsburg",
                       "Milan","Rome","Italy"]
print(choice(possible_destinations))

Milan


In [174]:
from numpy.random import choice
x2=choice(possible_destinations, size=(3,4))
print(x2)

[['London' 'Paris' 'Milan' 'Hamburg']
 ['Augsburg' 'Augsburg' 'Munich' 'Paris']
 ['Amsterdam' 'Italy' 'Italy' 'Paris']]


# You might have noticed that the cities names can have multiple occurrences. We can prevent this by setting the optional parameter "replace" to "False".

In [175]:
print(choice(possible_destinations, size=(3,4),replace=False))

[['Milan' 'Berlin' 'Augsburg' 'Paris']
 ['Italy' 'London' 'Rome' 'Heidelberg']
 ['Amsterdam' 'Zurich' 'Strasbourg' 'Munich']]


# Random Samples with Python

In [178]:
x = np.random.random_sample((3,4))

print(x)

[[0.675031   0.35233015 0.00322573 0.09129701]
 [0.39490051 0.21824904 0.0194597  0.78680297]
 [0.60494131 0.95666859 0.32280206 0.98010173]]


In [180]:
x = np.random.random_sample(7)
x

array([0.02009716, 0.35868381, 0.03687059, 0.57012127, 0.36069633,
       0.30395408, 0.92991194])

In [196]:
x = np.random.random_sample((7,2))
x

array([[0.60810656, 0.54784179],
       [0.9742943 , 0.60917882],
       [0.03728713, 0.44738944],
       [0.82757173, 0.9122241 ],
       [0.12801386, 0.36750228],
       [0.58564218, 0.00684201],
       [0.80418689, 0.01391009]])

In [ ]:
# 1. Create a null value of size 10 but the fifth value which is 1.
# 2. Create a numpy value ranging from 10 to 49.
# 3. Reverse the value (first element become the last).
# 4. Create a 3x3 matrix with values ranging from 0 to 8.
# 5. find the indices of non-zero elements from [1,2,0,0,4,0].
# 6. Create a 3x3 identity matrix
# 7. Create a 3x3x3 array with random values.
# 8. Create a 10x10 array with random values and find the minimum and mamimum values.
# 9. Create random number of size 30 and find the mean value.
# 10. Create a 2d array with 1 on the border and 0 inside.
# 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal.
# 12. Create a random value of size 10 and sort it.
# -----------------------------------End--------------------------------------------

In [5]:
# 1. Create a null value of size 10 but the fifth value which is 1.
import numpy as np

z=np.zeros(10)
z[4]=1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [6]:
# 2. Create a numpy value ranging from 10 to 49.
z=np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [8]:
# 3. Reverse the value (first element become the last).
z= np.arange(50)
z=z[::-1]
z

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [9]:
# 4. Create a 3x3 matrix with values ranging from 0 to 8.
z=np.arange(9).reshape(3,3)
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
# 5. find the indices of non-zero elements from [1,2,0,0,4,0].

l=np.array([1,2,0,0,4,0])
np.where(l)

(array([0, 1, 4], dtype=int64),)

In [11]:
nz=np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [13]:
# 6. Create a 3x3 identity matrix

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
x=np.eye(3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
# 7. Create a 3x3x3 array with random values.
z=np.random.random((3,3,3))
print(z)

[[[0.34158662 0.91012483 0.43667041]
  [0.39364164 0.82785621 0.6975901 ]
  [0.87222441 0.34966545 0.87653509]]

 [[0.64331809 0.89360008 0.98483531]
  [0.04245721 0.08297474 0.59503122]
  [0.45946696 0.28109201 0.23695549]]

 [[0.24382625 0.33662563 0.88818464]
  [0.60022565 0.93545551 0.21343221]
  [0.63689786 0.81335434 0.50820637]]]


In [24]:
# 8. Create a 10x10 array with random values and find the minimum and maximum values.

r=np.random.randint(1,40,size=(10,10))
r

array([[32, 22, 12, 24, 34, 13, 33, 20,  4, 26],
       [ 7, 24, 24,  8, 38, 33, 31, 11, 20, 15],
       [ 8, 21,  6, 17, 16, 39, 29, 20, 31, 33],
       [ 6, 39,  6, 36, 39, 12,  9, 36, 24,  5],
       [34, 34,  4,  2, 23,  6, 27,  8, 30, 36],
       [ 7, 26, 19, 24, 14, 26, 19,  6, 29, 30],
       [20, 33, 28, 30, 11, 32, 17, 12, 19, 37],
       [ 6, 17, 27,  9, 36, 18, 15,  1, 21, 15],
       [35, 25, 19, 35, 20, 17, 29, 24, 33, 11],
       [25, 16, 39, 23, 20, 34,  3, 33, 22, 20]])

In [29]:
z=np.random.random((10,10))
print(z)
zmin,zmax=z.min(),z.max()
print(zmin,zmax)

[[0.44646932 0.42648074 0.7925636  0.5890581  0.62943929 0.49132554
  0.53406991 0.05392298 0.10452174 0.55696618]
 [0.37171831 0.59883956 0.94257092 0.77940426 0.720199   0.13073834
  0.54592848 0.09652671 0.54508346 0.80418735]
 [0.33146296 0.40825623 0.86660816 0.62383644 0.14032277 0.27822797
  0.81636318 0.84147097 0.07084193 0.6626247 ]
 [0.92758765 0.17620864 0.16775231 0.25279271 0.20425622 0.00778499
  0.50552947 0.54835309 0.30598307 0.313325  ]
 [0.30255194 0.36832057 0.05712267 0.8942941  0.93491036 0.87667456
  0.76085414 0.42484677 0.10624386 0.58103731]
 [0.95546592 0.36806382 0.95981954 0.91395636 0.27635224 0.7781992
  0.48736514 0.44147378 0.46985279 0.46407026]
 [0.81712143 0.86403453 0.76672814 0.1275026  0.06882526 0.3308549
  0.29930278 0.10031739 0.95713728 0.80341585]
 [0.79558192 0.21956858 0.41284256 0.59372088 0.94537326 0.45501237
  0.08440066 0.16862466 0.07803112 0.50699769]
 [0.89610388 0.85213699 0.41348177 0.85049825 0.19101969 0.81694591
  0.77113522 0

In [31]:
# 9. Create random number of size 30 and find the mean value.
print(np.random.random(size=30))
r.mean()

[0.99446635 0.18987255 0.58507547 0.25172579 0.68435769 0.53611943
 0.14215345 0.01235047 0.91889901 0.34465461 0.05188103 0.57435778
 0.70949032 0.63593097 0.85927216 0.64151506 0.41539795 0.28080589
 0.41735976 0.60137761 0.40421226 0.90907802 0.41397745 0.45275607
 0.27779075 0.55094684 0.1092594  0.84779495 0.3979403  0.96154852]


21.54

In [32]:
z=np.random.random(30)
print(z)
m=z.mean()
print(m)

[0.76018295 0.86405297 0.01519799 0.73974988 0.84669922 0.53716679
 0.64503313 0.68443329 0.84314089 0.40582254 0.05534673 0.9266399
 0.07605832 0.59974373 0.78729154 0.76842917 0.79784236 0.75638048
 0.47582709 0.24854322 0.22757835 0.81912193 0.34534258 0.53247743
 0.59985249 0.11691176 0.64211648 0.09346971 0.70488781 0.41608306]
0.5443807928258889


In [34]:
# 10. Create a 2d array with 1 on the border and 0 inside.

np.array([[1,1,1],[1,0,1],[1,1,1]])


array([[1, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [60]:
x=np.ones((5,5))
print('original array:')
print(x)
x[1:-1,1:-1]=0
x

original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [44]:
row=5
col=5

array=[[1 if i==0 or i==row-1 or j==0 or j==col-1 else 0 for j in range(col)] for i in range(row)]
for row in array:
    print(row)

[1, 1, 1, 1, 1]
[1, 0, 0, 0, 1]
[1, 0, 0, 0, 1]
[1, 0, 0, 0, 1]
[1, 1, 1, 1, 1]


In [45]:
z=np.ones((5,5))
z[1:-1,1:-1]=0
z

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [42]:
# 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal.

matrix = np.zeros((5,5))
for i in range(1,5):
    matrix[i,i-1]=i
print(matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


In [49]:
# 12. Create a random value of size 10 and sort it.

j=np.random.random(size=10)
j.sort()
j

array([0.03851234, 0.12405212, 0.36557762, 0.45125959, 0.47590726,
       0.47638795, 0.50764412, 0.59827096, 0.75745667, 0.81640472])

In [62]:
arr=np.array([1,2,3,4,5,6,7])
print(arr[:4])


[1 2 3 4]


In [63]:
print(arr[-3:-1])

[5 6]


In [64]:
z=np.ones((5,5))
z[1:-1,1:-1]=0
z

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [67]:
print(arr[1:5:2])

[2 4]


In [68]:
print(arr)
print(arr[::2])

[1 2 3 4 5 6 7]
[1 3 5 7]


In [69]:
arr=np.array([[0,0,0,0,0],[0,0,0,0,0]])
arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [74]:
arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [77]:
print(arr[0:2])

[[0 0 0 0 0]
 [0 0 0 0 0]]


In [3]:
import numpy as np

# Create a 2D array of zeros
array = np.zeros((3, 3))

# Set the border elements to 1
array[0, :] = 1
array[-1, :] = 1
array[:, 0] = 1
array[:, -1] = 1

print(array)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


In [4]:
array[1:-1,1:-1]

array([[0.]])

In [5]:
z=np.ones((5,5))
z[1:-1,1:-1]=0
z

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
z[1:-1,1:-1]=56 # 1 is the column index and -1 is subtracted from lower column and : 1 is the rows index and -1 is subtracted from the backward rows value.
z   

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1., 56., 56., 56.,  1.],
       [ 1., 56., 56., 56.,  1.],
       [ 1., 56., 56., 56.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [11]:
# # 10. Create a 2d array with 1 on the border and 0 inside.
import numpy as np
z=np.ones((5,5))
z[1:-1,1:-1]=10
z

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1., 10., 10., 10.,  1.],
       [ 1., 10., 10., 10.,  1.],
       [ 1., 10., 10., 10.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [18]:
t=np.ones((3,3))
t[1:-1,1:-1]

array([[1.]])

In [30]:
z=np.ones((10,10))
z[1:-1]
z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])